<a href="https://colab.research.google.com/github/WardahGul/Data-Science2/blob/main/20SW034_Lab04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Lab #04
RollNo#20SW034
Lab #04

Task #01

In [1]:
import numpy as np

# Create a 1D array of even numbers from 2 to 32 (inclusive)
even_no = np.arange(2, 34, 2)  # Stop at 34 to include 32

# Reshape the 1D array into a 2D array with shape (4, 4)
Z = even_no.reshape(4, 4)

print(Z)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


Task #02

In [2]:
X = np.arange(1, 26).reshape(5, 5)

# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X % 2 != 0]

print("Actual array X:")
print(X)

print("\nArray Y with only odd numbers from X:")
print(Y)

Actual array X:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Array Y with only odd numbers from X:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


Task #03

In [3]:
import numpy as np

# Use Broadcasting to create a 4 x 4 ndarray with consecutive columns
X = np.arange(1, 5)[:, np.newaxis] * np.ones((1, 4))

print(X)

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


Task#04